const provinces = [
  "Buenos Aires",
  "Ciudad Autónoma de Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

const universities = [
  {
    province: "Buenos Aires",
    universitiesList: [
      "Universidad Abierta Interamericana (UAI)",
      "Universidad de Buenos Aires (UBA)",
      "Universidad de San Andrés (UDESA)",
      "Universidad de San Isidro",
      "Universidad Nacional de General Sarmiento (UNGS)",
      "Universidad Nacional de La Matanza (UNLAM)",
      "Universidad Nacional de Lanús (UNLA)",
      "Universidad Nacional de Luján (UNLU)",
      "Universidad Nacional de Moreno",
      "Universidad Nacional Raúl Scalabrini Ortiz",
      "Universidad Tecnológica Nacional (UTN)",
      "Universidad Nacional de La Plata (UNLP)",
      "Universidad Argentina de la Empresa (UADE)",
      "Universidad Nacional del Oeste (UNO)",
      "Universidad de Congreso",
      "Universidad Nacional del Centro de la Pcia. de Bs. As. (UNICEN)",
    ],
  },
  {
    province: "Ciudad Autónoma de Buenos Aires",
    universitiesList: [
      "Universidad Austral",
      "Universidad Católica Argentina (UCA)",
      "Universidad de Belgrano (UB)",
      "Universidad de Buenos Aires (UBA)",
      "Universidad de Ciencias Empresariales y Sociales (UCES)",
      "Universidad de la Defensa Nacional",
      "Universidad de Palermo (UP)",
      "Universidad Tecnológica Nacional (UTN)",
      "Universidad Torcuato Di Tella (UTDT)",
      "Instituto Universitario de la Policía Federal Argentina (IUPFA)",
      "Instituto de Enseñanza Superior del Ejército (IESE)",
      "Instituto Universitario de Seguridad Marítima (IUSM)",
      "Instituto Universitario de Gendarmería Nacional",
      "Instituto Universitario Naval (INUN)",
      "Universidad Nacional de las Artes (UNA)",
      "Universidad Nacional de Tres de Febrero (UNTREF)",
      "Universidad Nacional de Luján (UNLU)",
      "Universidad Pedagógica Nacional",
    ],
  },
  {
    province: "Catamarca",
    universitiesList: [
      "Universidad Nacional de Catamarca",
      "Universidad FASTA",
      "Facultad de Ciencias de la Salud (UNCA)",
    ],
  },
  {
    province: "Chaco",
    universitiesList: [
      "Universidad de Ciencias Empresariales y Sociales (UCES)",
      "Universidad Nacional del Nordeste (UNNE)",
      "Universidad de la Cuenca del Plata",
      "Universidad Nacional del Chaco Austral (UNCAUS)",
      "Universidad Gastón Dachary",
      "Universidad Tecnológica Nacional (UTN)",
    ],
  },
  {
    province: "Chubut",
    universitiesList: [
      "Universidad Nacional del Comahue (UNCOMA)",
      "Universidad de Flores (UFLO)",
      "Universidad Nacional de la Patagonia San Juan Bosco (UNP)",
      "Universidad Tecnológica Nacional (UTN)",
    ],
  },
  {
    province: "Córdoba",
    universitiesList: [
      "Instituto Universitario del Gran Rosario (IUGR)",
      "Universidad Nacional de Córdoba (UNC)",
      "Universidad Blas Pascal (UBP)",
      "Universidad Nacional de Río Cuarto (UNRC)",
      "Universidad Católica de Córdoba (UCC)",
      "Universidad Nacional de Villa María (UNVM)",
      "Universidad Empresarial Siglo XXI (UES)",
      "Instituto Universitario Aeronáutico (IUA)",
      "Instituto Universitario de Ciencias Biomédicas de Córdoba",
      "Universidad Tecnológica Nacional (UTN)",
      "Universidad provincel de Córdoba",
      "Universidad de Ciencias Empresariales y Sociales",
      "Universidad de Belgrano (UB)",
    ],
  },
  {
    province: "Corrientes",
    universitiesList: [
      "Universidad de la Cuenca del Plata",
      "Universidad Nacional del Nordeste (UNNE)",
      "Universidad del Salvador (USAL)",
      "Instituto Universitario de Cs. de la Salud Fundación Barceló (FB)",
    ],
  },
  {
    province: "Entre Ríos",
    universitiesList: [
      "Universidad Autónoma de Entre Ríos (UADER)",
      "Universidad Adventista del Plata (UAPAR)",
      "Universidad Nacional de Entre Ríos (UNER)",
      "Universidad Católica Argentina (UCA)",
      "Universidad Nacional de Concepción del Uruguay (UCU)",
      "Universidad Tecnológica Nacional (UTN)",
    ],
  },
  {
    province: "Formosa",
    universitiesList: [
      "Universidad Nacional de Formosa (UNF)",
      "Universidad Nacional del Nordeste (UNNE)",
    ],
  },
  {
    province: "Jujuy",
    universitiesList: [
      "Universidad Nacional de Jujuy (UNJU)",
      "Universidad de Ciencias Empresariales y Sociales (UCES)",
      "Universidad Católica de Santiago del Estero (UCSE)",
    ],
  },
  {
    province: "La Pampa",
    universitiesList: [
      "Universidad Nacional de La Pampa (UNLPAM)",
      "Cruz Roja Argentina Filial Santa Rosa",
    ],
  },
  {
    province: "La Rioja",
    universitiesList: [
      "Universidad Nacional de La Rioja (UNLAR)",
      "Universidad Nacional de Chilecito (UNDEC)",
      "Universidad Tecnológica Nacional (UTN)",
      "Instituto Universitario de Cs. de la Salud Fundación Barceló (FB)",
    ],
  },
  {
    province: "Mendoza",
    universitiesList: [
      "Universidad Nacional de Cuyo (UNCU)",
      "Universidad Tecnológica Nacional (UTN)",
      "Universidad de Mendoza (UM)",
      "Universidad Juan Agustín Maza (UMAZA)",
      "Universidad de Congreso",
      "Universidad del Aconcagua (UDA)",
      "Universidad Champagnat",
      "Universidad Católica Argentina (UCA)",
      "Universidad Católica de Cuyo (UCCUYO)",
    ],
  },
  {
    province: "Misiones",
    universitiesList: [
      "Universidad Nacional de Misiones (UNAM)",
      "Universidad Nacional del Nordeste (UNNE)",
      "Universidad Gastón Dachary",
      "Universidad Nacional del Alto Uruguay",
    ],
  },
  {
    province: "Neuquén",
    universitiesList: [
      "Universidad Nacional del Comahue (UNCOMA)",
      "Universidad Tecnológica Nacional (UTN)",
      "Universidad de Flores (sede Neuquén)",
      "Instituto de Formación Superior",
    ],
  },
  {
    province: "Río Negro",
    universitiesList: [
      "Universidad Nacional de Río Negro (UNRN)",
      "Universidad Nacional del Comahue (UNCOMA)",
      "Instituto Balseiro (IB)",
      "Instituto Universitario Patagónico de las Artes",
    ],
  },
  {
    province: "Salta",
    universitiesList: [
      "Universidad Nacional de Salta (UNSA)",
      "Universidad Católica de Salta (UCASAL)",
    ],
  },
  {
    province: "San Juan",
    universitiesList: [
      "Universidad Nacional de San Juan (UNSJ)",
      "Universidad Católica de Cuyo (UCCUYO)",
      "Universidad de Congreso",
    ],
  },
  {
    province: "San Luis",
    universitiesList: [
      "Universidad Nacional de San Luís (UNSL)",
      "Universidad Nacional de Villa Mercedes",
      "Universidad provincel de la Punta (ULP)",
      "Universidad Nacional de los Comechingones",
      "Universidad Católica de Cuyo (UCCUYO)",
      "Universidad de Congreso",
    ],
  },
  {
    province: "Santa Cruz",
    universitiesList: [
      "Universidad Andina Simón Bolívar (UASB)",
      "Escuela Militar de Ingeniería (EMI)",
      "Universidad Nacional del Oriente (UNO)",
      "Universidad Nacional Ecológica",
      "Universidad Católica Boliviana San Pablo (UCB)",
      "Universidad Cristiana de Bolivia (UCEBOL)",
      "Universidad de la Amazonía Boliviana",
      "Universidad de los Andes (UDELOSANDES)",
      "Universidad para el Desarrollo y la Innovación",
      "Universidad Bethesda (UNIBETH)",
      "Universidad Privada Domingo Savio (UPDS)",
      "Universidad Tecnológica Privada de Sta. Cruz (UTEPSA)",
      "Universidad Central (UNICEN)",
      "Universidad Privada Boliviana (UPB)",
    ],
  },
  {
    province: "Santa Fe",
    universitiesList: [
      "Universidad Nacional de Rosario (UNR)",
      "Universidad Nacional del Litoral (UNL)",
      "Universidad Nacional de Rafaela",
      "Universidad Tecnológica Nacional (UTN)",
      "Universidad Católica de Santa Fe (UCSF)",
      "Universidad de Ciencias Empresariales y Sociales (UCES)",
      "Universidad Austral",
      "Instituto Universitario Italiano de Rosario (IUNIR)",
      "Instituto Universitario del Gran Rosario (IUGR)",
      "Universidad del Centro Educ. Latinoamericano (UCEL)",
      "Universidad Abierta Interamericana (UAI)",
      "Universidad Católica Argentina (UCA)",
      "Instituto Universitario IDEA",
    ],
  },
  {
    province: "Santiago del Estero",
    universitiesList: [
      "Universidad Nacional de Santiago del Estero (UNSE)",
      "Universidad Católica de Santiago del Estero (UCSE)",
    ],
  },
  {
    province: "Tierra del Fuego",
    universitiesList: [
      "Universidad Tierra del Fuego, Antártica e Islas del Atlántico Sur",
      "Universidad Tecnológica Nacional (UTN)",
      "Universidad de Ciencias Empresariales y Sociales (UCES)",
    ],
  },
  {
    province: "Tucumán",
    universitiesList: [
      "Universidad Nacional de Tucumán (San Miguel de Tucumán)",
      "Universidad Tecnológica Nacional (UTN)",
      "Universidad del Norte Santo Tomás de Aquino (UNSTA)",
      "Universidad de San Pablo - Tucumán (USPT)",
    ],
  },
];

module.exports = {
  provinces,
  universities,
};
