const EMPTY_FIELD = "EMPTY_FIELD";
const INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT";
const INVALID_PASSWORD_FORMAT = "INVALID_PASSWORD_FORMAT";
const DIFFERENT_PASSWORD = "DIFFERENT_PASSWORD";

module.exports = {
  EMPTY_FIELD,
  INVALID_EMAIL_FORMAT,
  INVALID_PASSWORD_FORMAT,
  DIFFERENT_PASSWORD,
};
